diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=D:/DEV CESAR/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
core.editor="C:\Users\berna\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
user.name=CesarABL73
user.email=ciberllakal64@gmail.com
credential.helper=store
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
user.name=CesarABL73
user.email=ciberllakal64@gmail.com
remote.origin.url=https://github.com/platanus-hack/platanus-hack-26-mx-team-15.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
